{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "version-service.serviceAccountName" . }}
  labels:
    {{- include "version-service.labels" . | nindent 4 }}
{{- end }}
