replicaCount: 1

image:
  repository: ghcr.io/your-org/version-service
  pullPolicy: IfNotPresent
  tag: ""

serviceAccount:
  create: true
  name: ""

service:
  type: NodePort
  port: 8000
  nodePort: 37453

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}

podAnnotations: {}

podLabels: {}

ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: Prefix
  tls: []

env: []

livenessProbe:
  enabled: true
  path: /
  initialDelaySeconds: 10
  periodSeconds: 10

readinessProbe:
  enabled: true
  path: /version
  initialDelaySeconds: 5
  periodSeconds: 5

podSecurityContext: null

securityContext: null
