replicaCount: 1

image:
  repository: 720736521509.dkr.ecr.ap-south-1.amazonaws.com/codeact
  pullPolicy: IfNotPresent
  tag: "0.1.0"

serviceAccount:
  create: true
  name: ""

service:
  type: NodePort
  port: 8000
  nodePort: 30080

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}

podAnnotations: {}

podLabels: {}

ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: Prefix
  tls: []

env: []

livenessProbe:
  enabled: true
  path: /
  initialDelaySeconds: 10
  periodSeconds: 10

readinessProbe:
  enabled: true
  path: /version
  initialDelaySeconds: 5
  periodSeconds: 5

podSecurityContext: null

securityContext: null
